amar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect  # Importe a função redirect

def redirect_to_login(request):
    return redirect('inventory:login')

urlpatterns = [
    path('', redirect_to_login),  # Redirecione a raiz para a página de login
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls')),
]

inventory/urls.py
# amar/inventory/urls.py

from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.default_view, name='default_view'),  # Add this line for the root URL
    path('login/', views.login, name='login'),
    path('user-registration/', views.user_registration, name='user_registration'),
    path('stock-control/', views.stock_control, name='stock_control'),
    path('add-item/', views.add_item, name='add_item'),  # URL para adicionar item ao estoque
    path('confirm-delete-item/<int:item_id>/', views.confirm_delete_item, name='confirm_delete_item'),  # URL para confirmação de exclusão
    path('delete-item/<int:item_id>/', views.delete_item, name='delete_item'),  # URL para excluir item do estoque
    path('edit-item/<int:item_id>/', views.edit_item, name='edit_item'),  # Nova URL para edição do item
    path('sales-balance/', views.sales_balance, name='sales_balance'),
]

inventory/models.py
from django.db import models

class User(models.Model):
    username = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=100)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.usuario


class Item(models.Model):
    data = models.DateField(null=True, blank=True)
    modelo = models.CharField(max_length=100)
    cor = models.CharField(max_length=50)
    tamanho = models.CharField(max_length=20)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    valor_venda = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    quantidade = models.PositiveIntegerField()

    def __str__(self):
        return self.model

inventory/forms.py
# inventory/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['data', 'modelo', 'cor', 'tamanho', 'valor', 'valor_venda', 'quantidade', ]

inventory/views.py
from django.shortcuts import render, redirect
from .models import User, Item
from .forms import ItemForm

def default_view(request):
    return redirect('inventory:login')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = User.objects.get(username=username, password=password)
            # Aqui você pode redirecionar para a tela de controle de estoque após o login bem-sucedido
            return redirect('inventory:stock_control')
        except User.DoesNotExist:
            # Aqui você pode exibir uma mensagem de erro de login inválido
            pass
    return render(request, 'inventory/login.html')

def user_registration(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        User.objects.create(username=username, password=password, email=email)
        # Aqui você pode redirecionar para a tela de login após o registro bem-sucedido
        return redirect('inventory:login')
    return render(request, 'inventory/user_registration.html')

def stock_control(request):
    items = Item.objects.all()
    return render(request, 'inventory/stock_control.html', {'items': items})


def add_item(request):
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('inventory:stock_control')

    else:
        form = ItemForm()

    return render(request, 'inventory/add_item.html', {'form': form})

def delete_item(request, item_id):
    item = Item.objects.get(pk=item_id)
    if request.method == 'POST':
        item.delete()
        return redirect('inventory:stock_control')
    return redirect('inventory:confirm_delete_item', item_id=item_id)

def confirm_delete_item(request, item_id):
    item = Item.objects.get(pk=item_id)
    return render(request, 'inventory/confirm_delete_item.html', {'item': item})

def edit_item(request, item_id):
    item = Item.objects.get(pk=item_id)
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('inventory:stock_control')
    else:
        form = ItemForm(instance=item)
    return render(request, 'inventory/edit_item.html', {'form': form})


def sales_balance(request):
    items = Item.objects.all()

    for item in items:
        valor_compra = item.valor or 0  # Tratar valor de compra como 0 se for None
        valor_venda = item.valor_venda or 0  # Tratar valor de venda como 0 se for None
        item.balance = item.quantidade * (valor_compra - valor_venda)

    return render(request, 'inventory/sales_balance.html', {'items': items})

inventory/templates/inventory/add_item.html
<!-- inventory/templates/inventory/add_item.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Adicionar Item</title>
</head>
<body>
    <h1>Adicionar Item</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Adicionar</button>
    </form>
</body>
</html>

inventory/templates/inventory/confirm_delete_item.html
<!-- inventory/templates/inventory/confirm_delete_item.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Confirmar Exclusão</title>
</head>
<body>
    <h1>Confirmar Exclusão</h1>
    <p>Você tem certeza que deseja excluir o item "{{ item.model }}" do estoque?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Sim, Excluir</button>
        <a href="{% url 'inventory:stock_control' %}">Cancelar</a>
    </form>
</body>
</html>

inventory/templates/inventory/edit_item.html
<!DOCTYPE html>
<html>
<head>
    <title>Editar Item</title>
    <style>
        /* Estilo do cabeçalho */
        header {
            background-color: #1E90FF; /* Azul "cor do mar" */
            color: white;
            padding: 20px;
            text-align: center;
        }

        /* Estilo do rodapé */
        footer {
            background-color: #1E90FF; /* Azul "cor do mar" */
            color: white;
            padding: 10px;
            text-align: center;
            position: absolute;
            bottom: 0;
            width: 100%;
        }

        /* Estilo da tabela */
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #1E90FF; /* Azul "cor do mar" */
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #1E90FF; /* Azul "cor do mar" */
            color: white;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #ddd;
        }

        /* Estilo do botão */
        .button {
            display: inline-block;
            background-color: #1E90FF; /* Verde */
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            font-size: 16px;
            margin-top: 10px;
        }

        /* Alinhamento dos campos de input */
        .form-container {
            display: table;
            width: 50%;
        }

        .form-row {
            display: table-row;
        }

        .form-row label,
        .form-row input {
            display: table-cell;
            padding: 8px;
            border: 1px solid #1E90FF; /* Azul "cor do mar" */
        }
    </style>
</head>
<body>
    <header>
        <h1>Controle de Estoque</h1>
    </header>

    <h1>Editar Item</h1>
    <form method="post" class="form-container">
        {% csrf_token %}
        <div class="form-row">
            <label for="{{ form.data.id_for_label }}">Data:</label>
            {{ form.data }}
        </div>
        <div class="form-row">
            <label for="{{ form.modelo.id_for_label }}">Modelo:</label>
            {{ form.modelo }}
        </div>
        <div class="form-row">
            <label for="{{ form.cor.id_for_label }}">Cor:</label>
            {{ form.cor }}
        </div>
        <div class="form-row">
            <label for="{{ form.tamanho.id_for_label }}">Tamanho:</label>
            {{ form.tamanho }}
        </div>
        <div class="form-row">
            <label for="{{ form.valor.id_for_label }}">Valor de Compra:</label>
            {{ form.valor }}
        </div>
        <div class="form-row">
            <label for="{{ form.valor_venda.id_for_label }}">Valor de Venda:</label>
            {{ form.valor_venda }}
        </div>
        <div class="form-row">
            <label for="{{ form.quantidade.id_for_label }}">Quantidade:</label>
            {{ form.quantidade }}
        </div>
        <div class="form-row">
            <button type="submit" class="button">Salvar</button>
            <a href="{% url 'inventory:stock_control' %}" class="button">Cancelar</a>
        </div>
    </form>

    <footer>
        © {{ current_year }} Lojas Amar. Todos os direitos reservados.
    </footer>
</body>
</html>

inventory/templates/inventory/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Login - Lojas Amar</title>
    <style>
        /* Estilo do body com imagem de fundo */
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            background-image: url("{% static 'img/img_fundo.jpg' %}");
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
            padding-top: 50px;
            margin: 0; /* Remover margens padrão */
        }

        /* Estilo da caixa de login */
        .login-box {
            width: 300px;
            margin: 0 auto;
            padding: 20px;
            background-color: rgba(255, 255, 255, 0.8); /* Cor translúcida */
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2); /* Sombra leve */
        }

        /* Estilo dos campos de entrada e botão */
        .login-box label, .login-box input[type="text"], .login-box input[type="password"], .login-box input[type="submit"] {
            display: block;
            width: 95%;
            padding: 10px;
            font-size: 16px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .login-box input[type="submit"] {
            background-color: #3399cc;
            color: #fff;
            border: none;
            cursor: pointer;
            width: 95%;
        }

        .login-box input[type="submit"]:hover {
            background-color: #1e7fba;
        }

        /* Estilo do logo */
        .logo {
            max-width: 200px;
            margin: 0 auto 20px; /* Centraliza o logo horizontalmente e adiciona espaço abaixo */
            border-radius: 5px;
            display: block;
        }
    </style>
</head>
<body>
    <div class="login-box">
        <img src="{% static 'img/logo.png' %}" class="logo" alt="Lojas Amar Logo">
    <h1> </h1>
    <form method="post">
        {% csrf_token %}
        <label for="username">Usuário:</label>
        <input type="text" name="username" required>
        <br>
        <label for="password">Senha:</label>
        <input type="password" name="password" required>
        <br>
        <input type="submit" value="Login">
    </form>
    <p> <a href="{% url 'inventory:user_registration' %}">Cadastrar usuário</a></p>
</body>
</html>

inventory/templates/inventory/sales_balance.html
<!DOCTYPE html>
<html>
<head>
    <title>Sales Balance</title>
</head>
<body>
    <h1>Balanço de Vendas</h1>
    <table>
        <tr>
            <th>Modelo</th>
            <th>Cor</th>
            <th>Quantidade</th>
            <th>Balanço das Vendas</th>
        </tr>
        {% for item in items %}
        <tr>
            <td>{{ item.modelo }}</td>
            <td>{{ item.cor }}</td>
            <td>{{ item.quantidade }}</td>
            <td>R$ {{ item.balance }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

inventory/templates/inventory/stock_control.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Controle de Estoque</title>
    <style>
        /* Estilo do cabeçalho */
        header {
            background-color: #1E90FF; /* Azul "cor do mar" */
            color: white;
            padding: 20px;
            text-align: center;
        }

        /* Estilo do rodapé */
        footer {
            background-color: #1E90FF; /* Azul "cor do mar" */
            color: white;
            padding: 10px;
            text-align: center;
            position: absolute;
            bottom: 0;
            width: 100%;
        }

        /* Estilo dos botões */
        .button {
            display: inline-block;
            background-color: #1E90FF; /* Azul "cor do mar" */
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            font-size: 16px;
            margin-top: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        .button:hover {
            background-color: #1874CD; /* Azul mais escuro ao passar o mouse */
        }

        /* Estilo da tabela */
        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #F0F8FF; /* Azul claro para o cabeçalho da tabela */
        }

        tr:nth-child(even) {
            background-color: #F0F8FF; /* Azul claro para linhas pares */
        }

        tr:hover {
            background-color: #E6E6FA; /* Azul mais claro ao passar o mouse */
        }

        /* Estilo do container dos botões */
        .button-container {
            margin-top: 10px;
        }

        .button-container .button {
            margin-right: 10px;
        }
    </style>
</head>
<body>
    <header>
        <h1>Controle de Estoque</h1>
    </header>
    <table>
        <tr>
            <th>Data</th>
            <th>Modelo</th>
            <th>Cor</th>
            <th>Tamanho</th>
            <th>Valor de Compra</th>
            <th>Valor de Venda</th>
            <th>Quantidade</th>
            <th>Ações</th>
        </tr>
        {% for item in items %}
        <tr>
            <td>{{ item.data }}</td>
            <td>{{ item.modelo }}</td>
            <td>{{ item.cor }}</td>
            <td>{{ item.tamanho }}</td>
            <td>R$ {{ item.valor }}</td>
            <td>R$ {{ item.valor_venda }}</td>
            <td>{{ item.quantidade }}</td>
            <td>
                <a href="{% url 'inventory:edit_item' item.id %}" class="button">Editar</a>
                <a href="{% url 'inventory:delete_item' item.id %}" class="button">Excluir</a>
            </td>
        </tr>
        {% endfor %}
    </table>

    <div class="button-container">
        <a href="{% url 'inventory:add_item' %}" class="button">Adicionar Item</a>
        <a href="{% url 'inventory:sales_balance' %}" class="button">Balanço das Vendas</a>
    </div>

    <footer>
        © {{ current_year }} Lojas Amar. Todos os direitos reservados.
    </footer>
</body>
</html>

inventory/templates/inventory/user_registration.html
<!-- amar/inventory/templates/inventory/user_registration.html -->
<!DOCTYPE html>
<html>
<head>
    <title>User Registration</title>
</head>
<body>
    <h1>User Registration</h1>
    <form method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" required>
        <br>
        <label for="password">Password:</label>
        <input type="password" name="password" required>
        <br>
        <label for="email">Email:</label>
        <input type="email" name="email" required>
        <br>
        <input type="submit" value="Register">
    </form>
</body>
</html>